security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Patient  # Utilisation de la classe Patient
                property: email  # Identification par email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_connexion  # Route vers la page de connexion
                check_path: app_connexion  # Vérification des identifiants
                username_parameter: email  # 👈 Ajout de cette ligne pour que Symfony utilise "email" au lieu de "_username"
                password_parameter: password
            logout:
                path: app_deconnexion  # Route de déconnexion
                invalidate_session: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/patient, roles: ROLE_PATIENT }
